builds:
  - binary: sj
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: sj-cli
    homepage: "https://github.com/splitjoin/sj-cli"
    tap:
      owner: splitjoin
      name: homebrew-splitjoin
    commit_author:
      name: muratsu
      email: murat@splitjoin.com

checksum:
  name_template: 'checksums.txt'